version: '3'

services:
  mysql:
    container_name: 'mysql'
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"

  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
