-- AlterTable
ALTER TABLE `deposits` MODIFY `status` ENUM('CREATED', 'PENDING', 'APPROVED', 'CANCELED', 'REPROVED') NOT NULL DEFAULT 'APPROVED';

-- AlterTable
ALTER TABLE `transfers` MODIFY `status` ENUM('CREATED', 'PENDING', 'APPROVED', 'CANCELED', 'REPROVED') NOT NULL DEFAULT 'APPROVED';

-- AlterTable
ALTER TABLE `withidrawals` MODIFY `status` ENUM('CREATED', 'PENDING', 'APPROVED', 'CANCELED', 'REPROVED') NOT NULL DEFAULT 'APPROVED';
